/*
	.read gameData.sql
*/

/* firstName Table (100 Users) */
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kamal","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kyle","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Philip","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Robert","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Warren","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Owen","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Norman","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Lawrence","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Keegan","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Amery","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Lev","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Curran","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Cade","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Dorian","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Plato","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ashton","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Reuben","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Carter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Aladdin","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Porter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jeremy","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Channing","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Myles","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Walter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Flynn","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Mufutau","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"William","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Yuli","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Acton","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Dieter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Cruz","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kasper","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Thaddeus","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Abel","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Garrett","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Scott","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Paul","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Blaze","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Honorato","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Emery","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Cairo","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Basil","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kelly","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Dylan","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Garth","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ezekiel","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Gareth","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Christian","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jesse","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Grant","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jescie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jessica","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Idola","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Freya","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Rhona","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Josephine","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Adrienne","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Evangeline","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Amethyst","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Sheila","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ella","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Colleen","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Carla","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Penelope","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Isabella","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Janna","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Carolyn","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Daryl","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jaquelyn","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Maisie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Aline","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Noel","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Morgan","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Karly","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ava","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Avye","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Quincy","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jaquelyn","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Virginia","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Eden","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ainsley","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Illiana","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ocean","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Imogene","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Nerea","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kellie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Shellie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Nita","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Regina","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Tanya","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Lareina","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Amy","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Blossom","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Noel","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Rhonda","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kimberley","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Brynne","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Whitney","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Portia","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Leilani","F");

/* Last Names (100) */
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Solis");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Noble");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Norton");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Peterson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Stanley");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cruz");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Watson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Winters");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Whitfield");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Jennings");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Dillard");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Serrano");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Henderson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Howell");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Albert");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Pruitt");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Weber");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Downs");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hutchinson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Arnold");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Madden");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Raymond");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Wyatt");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Fulton");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cleveland");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Knight");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Strong");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Gould");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcintyre");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Houston");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Caldwell");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hughes");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Burke");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Salinas");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Clemons");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Woodard");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Atkinson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Byrd");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Whitley");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Woods");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcknight");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cox");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Sargent");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Alford");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Murphy");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Schultz");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Rasmussen");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcneil");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Blake");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cunningham");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Miranda");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Monroe");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Wilder");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Meyer");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Weaver");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Carroll");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cain");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Shaffer");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Klein");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Pittman");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Farrell");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Moore");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cohen");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hatfield");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Houston");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Griffin");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hanson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"James");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Kelly");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Gonzalez");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Humphrey");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Branch");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Maddox");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Ewing");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Brooks");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cross");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Bright");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Snow");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Schmidt");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Clements");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Black");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hubbard");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Sampson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Barrera");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Blackburn");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Reynolds");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Combs");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cote");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcfarland");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Pace");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Walker");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Stephenson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"George");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Burke");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Erickson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Robles");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Joyce");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mullins");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Dudley");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Williamson");

/* address Table (100) */
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #158-705 Nec Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"616 Nulla St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 159, 2937 Cursus. Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #344-9884 Vestibulum Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"807-3544 Amet St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 982, 7911 Dictum Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 958, 2396 Neque. Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 270, 9090 Sagittis. St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 392, 4395 Aliquet, Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"304-8230 Lorem, Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"6277 Ornare Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"8581 Non, St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #620-3741 Sed Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #907-5515 In Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"854-4597 Massa St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"1820 Sem St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"581-4977 Arcu St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 310, 5651 Mattis Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"7107 Tincidunt, St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 527, 447 Pede Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #431-4652 Cum Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"7114 Fusce St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"918 Erat. Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #541-2153 Libero Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"596-5346 Auctor, Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 341, 9793 Nibh Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 989, 1261 Enim, Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #670-5672 Lectus. Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"3004 Ac Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"557-6358 Vestibulum St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #451-1653 Dolor Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #686-1666 Phasellus Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"731-6482 Mauris. Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 835, 4022 Accumsan Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"2253 Suspendisse Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"394-4779 Duis St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"699-5869 Pede. Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"5710 Magnis Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #522-491 Amet, Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #691-9903 Lorem St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"820-8561 Lectus Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 509, 4657 Vehicula. St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"508-1911 Rutrum Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"9000 Semper St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"283-1296 Erat Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"146-9281 Vulputate, Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"4544 Aliquet St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"731-6747 Mauris Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 968, 932 Tempus St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"656-4618 Eleifend Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"542-9292 Sit Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"7008 Sed Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #914-9021 Nec Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"218-6609 Orci. Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 268, 9353 Ut Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"562-5433 Ipsum Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #652-2286 Vivamus Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #766-3573 Vivamus Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 998, 5798 Urna. Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"4464 Dictum. Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"470-7182 Non Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"9316 Pede Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"927-2997 Sed Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #308-841 Est, Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"606-6464 In Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 773, 476 Tempus Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #761-6641 Luctus, St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"463-2668 Orci. Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #748-1541 Eget, Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #449-669 Facilisis. Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 260, 1485 Tempus Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #901-5676 Nec Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"3915 Scelerisque St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"301-7358 Aliquet Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"822 Morbi Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 946, 5351 Netus Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #684-9068 Accumsan Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 361, 6475 Aliquet, Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 537, 2277 Elit St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"3790 Elit, Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 244, 7034 Condimentum St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"7969 Nec Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"414-440 Augue Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"5356 Nunc. Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"4771 Ipsum Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #297-2301 Donec St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 110, 4108 Iaculis St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #220-2154 Varius St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 326, 6092 Mi Avenue");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #317-6039 Magnis Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"609-5974 Id, Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #620-5233 Lectus Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #130-2370 Sem. St.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"621-6049 At Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"Ap #601-6343 Cras Road");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 770, 1345 Mollis Av.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"2666 Lorem Street");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 272, 962 Varius Rd.");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"9559 Blandit Ave");
INSERT INTO `address` (`ID`,`address`) VALUES (NULL,"P.O. Box 399, 4126 Donec Avenue");

/*city Table (100) */
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Cranbrook");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Habay-la-Vieille");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Fusignano");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Strathcona County");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Catanzaro");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Serralunga d'Alba");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Rimbey");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Vï¿½lklingen");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Gagliano del Capo");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Bristol");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Crotta d'Adda");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Ipswich");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Chï¿½telet");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Cantley");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Wiekevorst");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Ladispoli");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Weelde");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Newmarket");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Carleton");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Wetteren");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Zaffelare");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"NeudÃ¶rfl");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Oyen");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Heide");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Serralunga d'Alba");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Duluth");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Glendale");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Mesoraca");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Coquitlam");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Innisfail");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Widooie");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Lutsel K'e");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Sï¿½lange");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Canora");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Ottawa-Carleton");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Calder");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Malartic");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Trois-Riviï¿½res");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Gaggio Montano");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Zeist");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Stekene");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Lodelinsart");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Guardia Perticara");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Sauris");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Mespelare");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Denny");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Beervelde");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Kassel");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Sandy");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Huntly");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Wellingborough");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Driekapellen");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Crowsnest Pass");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Lerwick");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Kidderminster");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Donnas");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Norman Wells");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Clare");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Wanzele");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Cabano");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Fort Providence");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Baarle-Hertog");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Columbia");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Osasco");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"San Lazzaro di Savena");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Lienz");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Valley East");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Francavilla in Sinni");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Forgaria nel Friuli");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Allentown");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Zwickau");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Kitscoty");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Rocky Mountain House");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Oostende");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Mignanego");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Cerami");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Meux");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Rocky View");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Meix-Devant-Virton");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Ernage");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Elx");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Ramsdonk");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Colico");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Melilla");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Gols");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Oldenburg");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Whitchurch-Stouffville");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Waterloo");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Premeno");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Porirua");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Gosselies");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Marano Lagunare");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Armstrong");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Bon Accord");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Yellowhead County");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Spoleto");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Hamm");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Fermont");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Halifax");
INSERT INTO `city` (`ID`,`city`) VALUES (NULL,"Hï¿½villers");


/*region Table (100) */
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Dorset");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Flevoland");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"HE");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"CA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SI");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"OÃ");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"TO");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Saarland");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Bretagne");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Dr");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Extremadura");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NU");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"HI");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"AC");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Alberta");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NW");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NI");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NT");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NT");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"MB");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Newfoundland and Labrador");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"CM");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"St");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Zeeland");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Alaska");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Nunavut");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Luxemburg");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Vb");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Waals-Brabant");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Upper Austria");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"BA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Styria");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SH");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"OK");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LU");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LimÃ³n");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LR");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LU");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NT");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"KR");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"EL");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SC");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Friesland");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"ON");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"U.");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"AR");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"G");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Essex");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"HE");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Noord Brabant");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Western Australia");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Li");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"North Island");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"N.");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"DE");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"San JosÃ©");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"VE");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Upper Austria");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"North Island");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"VT");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Au");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Ce");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"British Columbia");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"OV");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Prince Edward Island");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SC");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"U.");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"RJ");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Maryland");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"AragÃ³n");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"HE");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Prince Edward Island");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Bg");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Nord-Pas-de-Calais");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"EX");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"OÃ");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"OH");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NI");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"WY");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Rhineland-Palatinate");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"VI");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Oregon");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Minnesota");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Zuid Holland");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SK");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"SI");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"La Rioja");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Quebec");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"CT");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"YK");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"HE");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"NU");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Henegouwen");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"LA");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Massachusetts");
INSERT INTO `region` (`ID`,`region`) VALUES (NULL,"Prince Edward Island");


/*postal Table (100) */
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"1292");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"11804");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"2476LZ");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"17534-641");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"77975");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"7547");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"0956");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"2888");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"83400");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"H4E 2K6");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"87338");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"54390");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"2501");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"97200");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"1614");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"36434");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"2213");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"19255");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3250");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"7257");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"4123IV");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3029UV");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"78247");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"76044");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"S3X 3Y8");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"64548-976");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"50370");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"T8Y 9X6");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"97465");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"V4E 9K6");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"5625");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"71883");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"68721");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"11839");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"58216");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"32713");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"E1P 0K7");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"71305");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"65100-591");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"2302GM");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"95926");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"26351");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"54371");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"67783");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"16669");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"37662-550");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"17869");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"51911");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"40967");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"9273");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"19739");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"20900");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"44812");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"41253");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3062");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"32777");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"00162");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"14346");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"50150");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"94106");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"T3R 8N1");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"2362VP");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"6350");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"62106");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"30022");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3296");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"95573");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"69871");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"6388");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"68934-822");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"08879");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"7585");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"64411");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"E07 9GP");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3524");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"0042");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"9845DW");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"70928-549");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"P9G 2M4");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"90968-666");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"27551");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3379BL");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"80845");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"43481");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"3504KL");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"M5 0CW");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"91913");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"48555");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"78215");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"13866-618");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");
INSERT INTO `postal` (`ID`,`postal`) VALUES (NULL,"Xxxx");


/*country Table (100) */
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Iraq");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Pakistan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"British Indian Ocean Territory");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Holy See (Vatican City State)");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Malawi");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Croatia");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Samoa");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Dominican Republic");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Belgium");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Dominica");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Niue");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Guam");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Libya");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Guyana");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Brazil");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Korea, South");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Western Sahara");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Korea, South");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Heard Island and Mcdonald Islands");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Guinea");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Senegal");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Poland");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Sri Lanka");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Kiribati");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Turkmenistan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Morocco");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Holy See (Vatican City State)");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Cuba");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Netherlands");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Niger");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Belgium");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Australia");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Gabon");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Costa Rica");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Japan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Swaziland");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Italy");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Costa Rica");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Bonaire, Sint Eustatius and Saba");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Macao");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Kenya");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Saint Vincent and The Grenadines");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Thailand");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Virgin Islands, British");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Burkina Faso");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Albania");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Japan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Brazil");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Kyrgyzstan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Sri Lanka");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Lebanon");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"El Salvador");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Mali");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Ghana");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Rwanda");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Kiribati");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"United Arab Emirates");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Brazil");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Peru");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Mauritius");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"San Marino");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Saudi Arabia");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Nauru");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Benin");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Zimbabwe");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Bahamas");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"United States Minor Outlying Islands");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Italy");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Ethiopia");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Azerbaijan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Vanuatu");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Saint Kitts and Nevis");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"South Africa");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"South Sudan");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Qatar");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Venezuela");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Swaziland");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Central African Republic");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Belize");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Gibraltar");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Ã…land Islands");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Monaco");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Mozambique");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Marshall Islands");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Turks and Caicos Islands");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Greece");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Andorra");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Sweden");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Korea, North");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Puerto Rico");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Ireland");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Denmark");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Lesotho");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Aruba");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Gibraltar");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Lesotho");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Botswana");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Falkland Islands (Islas Malvinas)");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"United Arab Emirates");
INSERT INTO `country` (`ID`,`country`) VALUES (NULL,"Hong Kong");


/* passportID Table (100) */
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DK697181");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EU926051");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"BP864892");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HB055937");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"KZ611433");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GH593114");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RA018931");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"BL664938");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"YY914256");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"PC592639");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RK053464");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WG021311");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"IC373839");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"YX915202");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RD705354");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"QO789892");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XH921320");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GE284311");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"LW102648");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GF720749");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZL217519");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SK817922");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VL201694");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WS693083");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ND426623");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"CB489707");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FG839878");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NK794539");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SV234465");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OE459431");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"TE560345");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"TF427724");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"PM809565");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SD065383");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NK057405");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SO743099");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"MV043700");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WB744589");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"AV473520");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DB550445");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HN062061");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"CL650440");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GY755056");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DC125679");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EU548269");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RG466969");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XM545117");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FI989671");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"MH635222");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NS816515");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"CR967039");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JH839554");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VD733958");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RL030281");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XU868162");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ML549088");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FQ166753");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EP628437");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HE413038");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NY350232");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WM842383");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZL689052");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FA350746");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"QT169498");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"YV312152");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OF052674");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RB077434");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FM119098");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XI014630");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VK500247");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HL408840");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"IO226215");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OF608906");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JN647110");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"PP144557");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DV070126");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JX628681");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FO596702");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"IE777358");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EO627991");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VP362184");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SL441565");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SL347839");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"KA119127");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RO497244");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SX894541");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZT575960");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZV199366");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZC573011");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XB036445");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FA289989");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"UZ873533");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"QX009218");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HD185547");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OT656454");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JJ179505");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"KC633716");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WG448923");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SW932486");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VA375439");

/* occupation Table (100) */
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Able Seamen");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Account Collector");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Accounting Specialist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Adjustment Clerk");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Administrative Assistant");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Administrative Law Judge");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Administrative Service Manager");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Admiralty Lawyer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Adult Literacy and Remedial Education Teachers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Advertising Account Executive");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Advertising Agency Coordinator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Aeronautical & Aerospace Engineer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Aerospace Engineering Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Baggage Porters and Bellhops");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Baker (Commercial)");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ballistics Expert");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bank and Branch Managers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bank Examiner");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bank Teller");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Benefits Manager");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bicycle Mechanic");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Billing Specialist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bindery Machine Set-Up Operators");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bindery Machine Tender");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biological Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biology Professor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biomedical Engineer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biomedical Equipment Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Boat Builder");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Book Editor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Odor Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Hair Boiler");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Citrus Fruit Dryer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Crocodile Wrangler");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Fourtune Cookie Writer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Pet Detective");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Cheese Spayer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"IMAX Screen Cleaner");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Chimeny Sweeper");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Light Bender");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Odd Job Journalist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Proffessional Whistler");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Fountain Pen Repairer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Snake Milker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Wrinkle Chaser");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Rodeo Clown");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Cow Hoof Trimmer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Chicken Sexer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ostritch Babysitter");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Furniture Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Oyster Floater");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Neck Skewer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Adult Store Attendent");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Braille Translator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ski Slope Illustrator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Dog Food Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Gum Buster");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Fantasy Broker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Golf Ball Driver");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Whiskey Ambassador");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Nasty Stunt Producer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Weed Farmer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Dice Inspector");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Operating Engineers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Operations Management Analyst");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ophthalmic Laboratory Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Parking Lot Attendant");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Parole Officer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Parts Salesperson");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Court Reporter");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Craft Artist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Crane Operator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Door To Door Salesmen");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Dry Wall Installer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Economics Professor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Radio & TV Talk Show Host");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Equal Opportunity Representative");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Etchers and Engravers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Excavating Machine Operator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"School Psychologist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Scientific Linguist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Scientific Photographer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Social Worker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Sociology Professor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Soil Conservation Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Forensics Psychologist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Forest and Conservation Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Forest Engineer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Hardwood Floor Finisher");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Hazardous Materials Removal Worker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Textile Designer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Tile and Marble Setters");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Writer /Author");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Zoo Veterinarian");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Zoologist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Kindergarten Teacher");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Labor Relations Advisor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Laboratory Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Veterinary Assistant");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Video Engineer");

