/*
	.read gameData.sql
*/

/* firstName Table (100 Users) */
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kamal","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kyle","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Philip","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Robert","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Warren","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Owen","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Norman","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Lawrence","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Keegan","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Amery","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Lev","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Curran","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Cade","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Dorian","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Plato","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ashton","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Reuben","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Carter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Aladdin","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Porter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jeremy","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Channing","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Myles","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Walter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Flynn","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Mufutau","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"William","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Yuli","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Acton","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Dieter","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Cruz","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kasper","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Thaddeus","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Abel","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Garrett","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Scott","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Paul","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Blaze","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Honorato","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Emery","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Cairo","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Basil","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kelly","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Dylan","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Garth","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ezekiel","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Gareth","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Christian","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jesse","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Grant","M");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jescie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jessica","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Idola","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Freya","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Rhona","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Josephine","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Adrienne","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Evangeline","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Amethyst","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Sheila","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ella","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Colleen","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Carla","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Penelope","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Isabella","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Janna","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Carolyn","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Daryl","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jaquelyn","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Maisie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Aline","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Noel","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Morgan","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Karly","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ava","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Avye","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Quincy","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Jaquelyn","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Virginia","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Eden","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ainsley","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Illiana","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Ocean","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Imogene","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Nerea","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kellie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Shellie","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Nita","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Regina","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Tanya","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Lareina","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Amy","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Blossom","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Noel","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Rhonda","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Kimberley","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Brynne","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Whitney","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Portia","F");
INSERT INTO `firstName` (`ID`,`firstName`,`gender`) VALUES (NULL,"Leilani","F");

/* Last Names (100) */
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Solis");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Noble");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Norton");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Peterson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Stanley");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cruz");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Watson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Winters");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Whitfield");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Jennings");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Dillard");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Serrano");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Henderson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Howell");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Albert");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Pruitt");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Weber");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Downs");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hutchinson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Arnold");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Madden");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Raymond");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Wyatt");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Fulton");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cleveland");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Knight");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Strong");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Gould");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcintyre");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Houston");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Caldwell");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hughes");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Burke");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Salinas");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Clemons");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Woodard");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Atkinson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Byrd");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Whitley");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Woods");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcknight");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cox");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Sargent");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Alford");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Murphy");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Schultz");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Rasmussen");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcneil");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Blake");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cunningham");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Miranda");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Monroe");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Wilder");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Meyer");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Weaver");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Carroll");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cain");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Shaffer");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Klein");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Pittman");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Farrell");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Moore");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cohen");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hatfield");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Houston");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Griffin");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hanson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"James");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Kelly");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Gonzalez");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Humphrey");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Branch");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Maddox");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Ewing");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Brooks");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cross");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Bright");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Snow");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Schmidt");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Clements");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Black");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Hubbard");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Sampson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Barrera");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Blackburn");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Reynolds");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Combs");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Cote");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mcfarland");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Pace");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Walker");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Stephenson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"George");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Burke");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Erickson");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Robles");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Joyce");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Mullins");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Dudley");
INSERT INTO `lastName` (`ID`,`lastName`) VALUES (NULL,"Williamson");

/* address Table (100) */
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"811-2375 Tempus Rd.","Bonnyrigg","2700","Azerbaijan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 506, 7740 Ultrices Road","Balfour","28393","Palestine, State of");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #817-4676 Vel Ave","Idaho Falls","35828","Gambia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 486, 7358 Magna. Road","Paradise","81446","Bahrain");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"940-1136 Est Road","Neuville","09717","Montserrat");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 572, 2642 Luctus Avenue","Forst","5458","Philippines");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"2839 Sociis Rd.","Town of Yarmouth","47764","Malawi");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 419, 3000 Eget, Av.","Castiglione del Lago","39191","Nigeria");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"3089 Justo. Ave","Brye","M5J 8S9","British Indian Ocean Territory");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"1192 Nullam Street","Merchtem","60700","Angola");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"191-9448 Et Rd.","Watson Lake","3472","Algeria");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 355, 567 Eu, St.","Augusta","Xxxx","Honduras");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"4251 Adipiscing Rd.","St. John's","0744","Dominican Republic");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #566-8786 Purus Ave","Zweibr?cken","45116","Turkmenistan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 567, 6370 Duis Road","Beaufays","3150","Norway");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"7158 A St.","Weiz","9140SD","Mongolia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"4710 Diam. Avenue","Tilff","35200","Vanuatu");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 288, 7706 Mauris. Av.","Penrith","02553","Bosnia and Herzegovina");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #253-8964 Etiam Rd.","Dworp","43239-407","Serbia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"891-2388 Sed, Rd.","San Costantino Calabro","U2 4DM","Guadeloupe");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"9053 Duis St.","Saint-Pierre","16817","Suriname");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 730, 1999 Dignissim Ave","Monte San Giovanni in Sabina","CW42 9QX","New Zealand");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #271-5098 Tempor Ave","Ancona","1960","Slovakia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 887, 9226 Posuere, Rd.","Cles","V7W 7M2","Holy See (Vatican City State)");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 567, 1881 Curabitur Rd.","Lithgow","E8Q 1RK","Mauritius");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"2979 Massa Road","Moerkerke","51502","Uzbekistan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"2572 Lacus. Avenue","Morrinsville","60009","Saint Helena, Ascension and Tristan da Cunha");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"772-6972 Sed St.","San Diego","89261","Spain");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 179, 7400 Amet, Ave","Pointe-du-Lac","Xxxx","El Salvador");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"1881 Hendrerit Road","M?hlheim am Main","33405","CuraÃ§ao");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #573-4967 Arcu. Ave","Vucht","SI3D 4TN","South Africa");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 438, 5445 Cras Av.","Bassiano","Xxxx","New Caledonia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #792-5040 Elementum, Rd.","Cras-Avernas","79918-642","United States");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"3101 Dictum Avenue","Owensboro","13469-218","Taiwan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #764-9497 Suspendisse Av.","St. Albans","79204","Italy");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #107-8431 Nullam Avenue","Gualdo Tadino","25854","Congo, the Democratic Republic of the");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"167-1478 Nulla. St.","Ficarolo","41208","Georgia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 417, 1311 Pede. Street","Villa Cortese","95634","Nepal");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 547, 125 Aliquet Ave","San Luca","9520","Libya");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #796-1498 Fusce Road","Sant'Agata Bolognese","56028","Iraq");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"543-4221 Quisque Street","Salzgitter","43433","Bosnia and Herzegovina");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"1919 Tellus Rd.","Whitby","82498","Sudan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #261-3260 Vitae Rd.","Thorembais-Saint-Trond","64656-568","Tuvalu");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 682, 8180 Ante. Street","Colchester","X2T 0P6","Tuvalu");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"9400 Nunc Street","Zierikzee","2058","Haiti");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 125, 1539 Euismod Rd.","Genzano di Lucania","N06 1MT","Yemen");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"293-4030 Aliquet Rd.","Cametá","41214","Slovakia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"693-2554 Tempus, Ave","San Mauro Marchesato","K3P 7N9","Lesotho");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"526-2909 Magnis Avenue","Cargovil","J1V 7W9","Saudi Arabia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"8213 Ipsum Av.","Leeds","5554","Kazakhstan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"5669 In Rd.","Campbeltown","9750","Rwanda");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"8163 Metus. Ave","Cáceres","Xxxx","Mali");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"8100 Dignissim Rd.","Boston","1601","Fiji");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 536, 3402 Velit. Rd.","Solre-Saint-G?ry","69791","Viet Nam");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"2766 Non Av.","Dawson Creek","8016","British Indian Ocean Territory");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"5725 Eleifend Street","Riksingen","5703","Guinea");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"104-4519 Magna. Street","Opoeteren","12186","Panama");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 875, 4265 Ac Av.","Salerno","G8B 6N6","Saint Lucia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 568, 3191 Fusce Rd.","Ceuta","5270","Faroe Islands");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"5284 Erat. Avenue","San Damiano al Colle","50709","Qatar");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"2263 Nunc Ave","Temploux","Xxxx","Yemen");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 902, 269 Maecenas Ave","Casoli","28185","Somalia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #489-596 Maecenas St.","Ried im Innkreis","0950","Tokelau");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #199-637 Integer Avenue","Merbes-le-Ch?teau","13200","Mongolia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #531-653 Sed Av.","Bottrop","Xxxx","Oman");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"1108 Ante Rd.","San Nicolás","07976-937","Guadeloupe");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"1258 Mauris, Ave","Hérouville-Saint-Clair","18258","Rwanda");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 491, 5754 Malesuada Rd.","Edmonton","8438KI","Turkey");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"621-2619 Maecenas Road","Reno","06431","Pitcairn Islands");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #927-595 Augue St.","Herstal","64185-700","Armenia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"4472 Adipiscing Street","Cour-sur-Heure","9041","Wallis and Futuna");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"5684 Penatibus Ave","Castelnovo del Friuli","8500","Romania");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 818, 685 Blandit Rd.","Reno","1863VQ","Bonaire, Sint Eustatius and Saba");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 779, 4625 Ultricies Rd.","Norfolk","43548","Moldova");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #486-9572 Sed Rd.","Fort Smith","41693","Malta");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"5992 Sit Street","Liverpool","1933US","Brazil");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"499-8428 Accumsan Rd.","Dorval","87140-051","Luxembourg");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"9952 Laoreet Ave","Bad Ischl","1118AI","Andorra");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 201, 3029 Vulputate, Av.","Campbelltown","41867","Botswana");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"174 Consequat, Av.","Campolieto","41914","Papua New Guinea");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"2216 Nisi St.","Wilmington","3680","Mauritius");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"3344 In Av.","Toulon","07991","Sierra Leone");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 735, 6326 Semper, St.","Sta?furt","75370","Tokelau");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 893, 7147 Mauris Ave","Rae Lakes","41006","Bangladesh");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"4382 Metus. Street","Itapipoca","67755","Venezuela");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"874-3898 Iaculis, St.","Peterborough","23488","Bahrain");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #649-778 Nonummy Rd.","Delft","5964","Isle of Man");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"755 Proin Street","Gosselies","17242-023","Armenia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"7088 Lacinia Av.","Hoyerswerda","V9 1XS","French Polynesia");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"5116 Dictum Road","Etalle","44706","Netherlands");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 945, 5017 Commodo Ave","Houtain-le-Val","89477","Philippines");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 769, 5062 Gravida Ave","Cajazeiras","77826","China");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #821-3944 Tristique Avenue","Scunthorpe","51236-371","Samoa");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"729-5058 Iaculis Street","Kincardine","48911","Bermuda");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 743, 7009 Vitae Rd.","Delta","Y9V 4B4","Haiti");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"P.O. Box 293, 5419 Sed Avenue","Cupar","48923","Papua New Guinea");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"825-6625 Sed, St.","Leers-et-Fosteau","21111","Guinea");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"1571 Eu Road","Hoeke","60102","Ecuador");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"Ap #333-7418 Purus. Road","San Marcello Pistoiese","2119","Uzbekistan");
INSERT INTO `address` (`ID`,`address`,`city`,`postal`,`country`) VALUES (NULL,"270-7135 Feugiat Rd.","Ajaccio","55349","Niger");

/* driversID Table (100) 
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5673745);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2731259);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6989885);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5716071);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2072578);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4224554);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7596658);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1268178);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5564509);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8468087);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6132874);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6249660);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3725755);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6403555);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4330600);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5964066);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6030371);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1621301);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5852126);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2493244);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2838142);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7555869);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1439815);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7600729);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1237180);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8163804);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9248926);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7550517);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1408891);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9773299);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3482984);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6082637);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2504558);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9472869);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1798708);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3577136);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3697424);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8395367);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3845315);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8261934);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6863455);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8978189);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4511594);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9589211);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5381745);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7842195);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5553277);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1412116);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8463497);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1405403);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2905360);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1301639);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7961273);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3345176);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7902369);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8198453);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1508981);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7151295);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5748971);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1917872);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6924594);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8231955);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7000510);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8429153);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7704825);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7799219);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2006290);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1402250);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6194586);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4851605);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8664184);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3058042);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3829795);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3175779);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2647253);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8211540);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1017974);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7200530);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8623656);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8481471);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,7605934);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,1529017);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8783111);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5567208);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3874193);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6685480);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3765662);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4383174);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,3836776);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8514634);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5301047);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9761371);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,6746589);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,2301557);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,8190524);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4451415);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9100777);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,9196814);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,4853665);
INSERT INTO `driversID` (`ID`,`driversID`) VALUES (NULL,5295364); */

/* passportID Table (100) */
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DK697181");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EU926051");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"BP864892");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HB055937");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"KZ611433");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GH593114");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RA018931");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"BL664938");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"YY914256");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"PC592639");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RK053464");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WG021311");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"IC373839");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"YX915202");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RD705354");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"QO789892");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XH921320");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GE284311");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"LW102648");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GF720749");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZL217519");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SK817922");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VL201694");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WS693083");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ND426623");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"CB489707");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FG839878");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NK794539");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SV234465");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OE459431");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"TE560345");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"TF427724");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"PM809565");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SD065383");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NK057405");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SO743099");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"MV043700");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WB744589");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"AV473520");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DB550445");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HN062061");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"CL650440");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"GY755056");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DC125679");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EU548269");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RG466969");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XM545117");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FI989671");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"MH635222");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NS816515");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"CR967039");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JH839554");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VD733958");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RL030281");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XU868162");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ML549088");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FQ166753");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EP628437");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HE413038");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"NY350232");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WM842383");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZL689052");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FA350746");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"QT169498");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"YV312152");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OF052674");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RB077434");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FM119098");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XI014630");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VK500247");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HL408840");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"IO226215");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OF608906");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JN647110");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"PP144557");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"DV070126");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JX628681");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FO596702");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"IE777358");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"EO627991");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VP362184");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SL441565");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SL347839");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"KA119127");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"RO497244");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SX894541");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZT575960");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZV199366");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"ZC573011");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"XB036445");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"FA289989");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"UZ873533");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"QX009218");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"HD185547");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"OT656454");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"JJ179505");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"KC633716");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"WG448923");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"SW932486");
INSERT INTO `passportID` (`ID`,`passportID`) VALUES (NULL,"VA375439");

/* occupation Table (100) */
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Able Seamen");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Account Collector");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Accounting Specialist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Adjustment Clerk");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Administrative Assistant");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Administrative Law Judge");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Administrative Service Manager");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Admiralty Lawyer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Adult Literacy and Remedial Education Teachers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Advertising Account Executive");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Advertising Agency Coordinator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Aeronautical & Aerospace Engineer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Aerospace Engineering Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Baggage Porters and Bellhops");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Baker (Commercial)");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ballistics Expert");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bank and Branch Managers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bank Examiner");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bank Teller");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Benefits Manager");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bicycle Mechanic");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Billing Specialist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bindery Machine Set-Up Operators");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Bindery Machine Tender");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biological Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biology Professor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biomedical Engineer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Biomedical Equipment Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Boat Builder");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Book Editor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Odor Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Hair Boiler");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Citrus Fruit Dryer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Crocodile Wrangler");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Fourtune Cookie Writer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Pet Detective");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Cheese Spayer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"IMAX Screen Cleaner");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Chimeny Sweeper");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Light Bender");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Odd Job Journalist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Proffessional Whistler");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Fountain Pen Repairer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Snake Milker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Wrinkle Chaser");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Rodeo Clown");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Cow Hoof Trimmer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Chicken Sexer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ostritch Babysitter");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Furniture Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Oyster Floater");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Neck Skewer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Adult Store Attendent");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Braille Translator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ski Slope Illustrator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Dog Food Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Gum Buster");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Fantasy Broker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Golf Ball Driver");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Whiskey Ambassador");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Nasty Stunt Producer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Weed Farmer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Dice Inspector");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Operating Engineers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Operations Management Analyst");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Ophthalmic Laboratory Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Parking Lot Attendant");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Parole Officer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Parts Salesperson");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Court Reporter");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Craft Artist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Crane Operator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Door To Door Salesmen");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Dry Wall Installer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Economics Professor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Radio & TV Talk Show Host");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Equal Opportunity Representative");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Etchers and Engravers");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Excavating Machine Operator");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"School Psychologist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Scientific Linguist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Scientific Photographer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Social Worker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Sociology Professor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Soil Conservation Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Forensics Psychologist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Forest and Conservation Technician");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Forest Engineer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Hardwood Floor Finisher");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Hazardous Materials Removal Worker");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Textile Designer");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Tile and Marble Setters");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Writer /Author");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Zoo Veterinarian");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Zoologist");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Kindergarten Teacher");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Labor Relations Advisor");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Laboratory Tester");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Veterinary Assistant");
INSERT INTO  'occupation' ('ID','occupation') values (NULL,"Video Engineer");

/* dob Table (100) 
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"18/02/93");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"13/09/76");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"30/08/33");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"15/03/89");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"27/06/76");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"24/03/31");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"07/01/72");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"10/11/21");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"06/06/78");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"19/01/43");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"28/02/53");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"08/09/89");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"01/10/57");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"20/02/77");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"21/10/66");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"08/11/47");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"05/10/91");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"10/01/15");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"17/04/83");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"28/02/63");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"12/07/21");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"21/10/17");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"24/03/62");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"06/12/75");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"02/07/84");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"20/12/72");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"30/05/65");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"16/08/56");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"15/03/96");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"13/10/75");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"18/03/86");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"05/07/69");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"15/03/64");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"10/12/54");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"27/01/25");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"03/04/46");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"03/03/79");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"19/11/72");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"29/10/17");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"29/04/40");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"16/10/28");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"20/08/41");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"03/06/96");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"29/04/96");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"12/04/81");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"14/12/28");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"02/05/58");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"04/08/35");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"01/07/88");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"01/09/43");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"04/08/73");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"04/02/77");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"25/04/92");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"04/01/16");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"01/05/45");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"23/12/82");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"12/09/83");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"29/05/68");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"11/01/20");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"05/02/72");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"07/01/64");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"08/01/26");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"14/04/95");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"03/03/69");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"30/06/64");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"29/11/45");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"24/01/46");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"20/10/90");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"14/06/89");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"15/12/21");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"28/02/83");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"31/03/21");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"02/10/24");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"10/07/75");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"10/01/16");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"25/11/91");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"18/07/82");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"19/08/93");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"27/02/55");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"21/04/84");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"02/02/86");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"23/03/57");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"28/01/68");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"15/07/65");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"22/07/65");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"21/02/38");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"24/05/42");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"06/01/19");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"23/06/90");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"25/05/96");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"24/09/52");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"19/07/56");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"27/11/92");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"09/02/24");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"10/08/87");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"08/01/24");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"18/11/23");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"14/05/63");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"12/03/46");
INSERT INTO `dob` (`ID`,`dob`) VALUES (NULL,"13/10/29"); */

/* state Table (5) 
INSERT INTO 'state' ('state') VALUES (0);
INSERT INTO 'state' ('state') VALUES (1);
INSERT INTO 'state' ('state') VALUES (2);
INSERT INTO 'state' ('state') VALUES (3);
INSERT INTO 'state' ('state') VALUES (4); */

/* misc Table ??? */
